[project]
name = "utilotest"
version = "1.0.4"
description = ""
requires-python = ">=3.12"
authors = [
    { name = "Helmut Konrad Schewe", email = "helmutus@outlook.com" },
]
dependencies = [
    "configos>=1.0.4,<2.0.0",
    "pytest>=9.1.1,<10.0.0",
    "resinf>=1.0.4,<2.0.0",
    "utilo>=2.109.1,<3.0.0",
]
keywords = []
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
license = "MIT"
license-files = [
    "LICENSE",
]

[project.readme]
file = "README"
content-type = "text/markdown"

[project.scripts]
collect_trace = "utilotest.cli.tracer:main"

[project.optional-dependencies]
dev = [
    "hoverpower>=1.5.2,<2.0.0",
    "pytest_localserver==0.10.0",
    "selenium==4.46.0",
]

[project.urls]
Homepage = "https://github.com/anaticulae/utilotest"
Repository = "https://github.com/anaticulae/utilotest"

[build-system]
requires = [
    "setuptools>=83.0.0",
    "wheel>=0.47.0",
]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:project.version",
]

[tool.semantic_release.changelog]
mode = "init"
output_format = "md"

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG"

[tool.semantic_release.commit_parser_options]
patch_tags = [
    "build",
    "chore",
    "ci",
    "deps",
    "docs",
    "fix",
    "perf",
    "refactor",
    "style",
    "test",
]
minor_tags = [
    "feat",
]

[tool.setuptools.packages.find]
where = [
    ".",
]
include = [
    "utilotest",
    "utilotest.cli",
    "viewvisitor",
]
exclude = [
    "tests*",
]

[tool.setuptools.package-data]
viewvisitor = [
    "fuchs/*",
]
